#!/usr/bin/env bash
# Evidence driver: runs the COMPLETE claude launch line that the real
# bin/fm-spawn.sh generates for a ship worker (not just its --settings JSON)
# in a real interactive pty (private tmux server), in the worker's worktree,
# with claude's API pointed at a local capture server. Asserts what the first
# model request actually carried. Spends no model tokens.
#
# Usage: drive-full-launch.sh <worktree-root> <case-label> <home-dir-name> <layout: nested|outside|symlink>
set -u
ROOT=$1 LABEL=$2 HOMENAME=$3 LAYOUT=$4
# shellcheck source=/dev/null
. "$ROOT/tests/fixtures.sh"
EVID=${EVID:?}
TMP=$(mktemp -d /tmp/fm-nest-drive.XXXXXX)
SOCK="fmnest-$$"
cleanup() { tmux -L "$SOCK" kill-server 2>/dev/null; [ -n "${CAP_PID:-}" ] && kill "$CAP_PID" 2>/dev/null; sleep 2; rm -rf "$TMP" 2>/dev/null || { sleep 3; rm -rf "$TMP"; }; }
trap cleanup EXIT

HOME_REAL="$TMP/$HOMENAME"
fm_test_spawn_home "$HOME_REAL" claude
printf '@AGENTS.md\n' > "$HOME_REAL/CLAUDE.md"
printf 'HOME_CONTRACT_MARKER firstmate supervisor contract\n' > "$HOME_REAL/AGENTS.md"
PROJ="$HOME_REAL/projects/proj"
fm_git_init_commit "$PROJ"
printf 'PROJECT_MARKER project rules\n' > "$PROJ/CLAUDE.md"
printf '.treehouse/\n' > "$PROJ/.gitignore"
git -C "$PROJ" add -A && git -C "$PROJ" -c user.name=t -c user.email=t@t commit -qm project
fm_git_add_origin "$PROJ" "$PROJ.origin.git"
case "$LAYOUT" in
  outside) WT="$TMP/pool/1/proj" ;;
  *) WT="$PROJ/.treehouse/pool/1/proj" ;;
esac
mkdir -p "$(dirname "$WT")"
git -C "$PROJ" worktree add --quiet -b "wt-$LABEL" "$WT"
HOME_ARG=$HOME_REAL WT_ARG=$WT
if [ "$LAYOUT" = symlink ]; then
  # FM_HOME and the pane path reach the home through a symlink.
  ln -s "$HOME_REAL" "$TMP/homelink"
  HOME_ARG="$TMP/homelink"
  WT_ARG="$HOME_ARG/projects/proj/.treehouse/pool/1/proj"
fi

FAKEBIN=$(fm_test_make_spawn_fakebin "$TMP/fake")
fm_test_spawn_brief "$HOME_ARG" "t-$LABEL" "Reply with the word ok."
LOG="$TMP/launch.log"; : > "$LOG"
SPAWN_OUT=$(FM_FAKE_LAUNCH_LOG="$LOG" PATH="$FAKEBIN:$PATH" fm_test_run_spawn "$HOME_ARG" "$WT_ARG" "$FAKEBIN" \
  "t-$LABEL" "$HOME_ARG/projects/proj" --harness claude --mode no-mistakes --yolo off) || { echo "SPAWN FAILED: $SPAWN_OUT"; exit 1; }
LAUNCH=$(grep -m1 'claude ' "$LOG")
{
  echo "### case: $LABEL (layout=$LAYOUT, home=$HOME_ARG)"
  echo "### fm-spawn stderr/stdout (warnings only):"; printf '%s\n' "$SPAWN_OUT" | grep -i 'warning' || echo "(none)"
  echo "### launch line generated by fm-spawn:"; printf '%s\n' "$LAUNCH"
} > "$EVID/full-launch-$LABEL.txt"

# Isolated claude config with trust + external-import consent for every dir.
CFG="$TMP/claude-config"; mkdir -p "$CFG"
e='{hasTrustDialogAccepted: true, hasClaudeMdExternalIncludesApproved: true, hasClaudeMdExternalIncludesWarningShown: true}'
# NO_CONSENT=1: no pre-approved external-import consent, as on a fresh project entry.
[ "${NO_CONSENT:-}" = 1 ] && e='{hasTrustDialogAccepted: true}'
jq -n --arg p "$(cd "$PROJ" && pwd -P)" --arg n "$(cd "$WT" && pwd -P)" --arg h "$HOME_REAL" --arg w "$WT_ARG" --arg k "sk-ant-capture-only-000000000000" \
  "$e as \$e | {hasCompletedOnboarding: true, bypassPermissionsModeAccepted: true, theme: \"dark\", customApiKeyResponses: {approved: [(\$k|.[-20:])], rejected: []}, projects: {(\$p): \$e, (\$n): \$e, (\$h): \$e, (\$w): \$e}}" > "$CFG/.claude.json"

printf '{"skipDangerousModePermissionPrompt":true}\n' > "$CFG/settings.json"
CAP="$TMP/cap"; mkdir -p "$CAP"
python3 "$EVID/capture.py" "$CAP" 2>/dev/null & CAP_PID=$!
i=0; while [ ! -s "$CAP/port" ] && [ $i -lt 100 ]; do sleep 0.05; i=$((i+1)); done
PORT=$(cat "$CAP/port")

RUN="$TMP/run.sh"
{
  echo "cd $(printf '%q' "$WT_ARG")"
  echo "unset CLAUDECODE CLAUDE_CODE_ENTRYPOINT"
  echo "export CLAUDE_CONFIG_DIR=$(printf '%q' "$CFG") ANTHROPIC_API_KEY=sk-ant-capture-only-000000000000 ANTHROPIC_BASE_URL=http://127.0.0.1:$PORT CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 ANTHROPIC_MODEL=claude-haiku-4-5"
  printf '%s\n' "$LAUNCH"
} > "$RUN"
tmux -L "$SOCK" new-session -d -x 200 -y 50 "bash --norc $RUN; sleep 30"
body=
for _ in $(seq 1 120); do
  # The main agent request is the one carrying the brief AND the tool
  # definitions (claude sends small side queries first); pick the largest.
  body=$(grep -l 'Reply with the word ok' "$CAP"/[0-9]*.json 2>/dev/null | xargs -r ls -S 2>/dev/null | head -n1)
  [ -n "$body" ] && [ "$(wc -c <"$body")" -lt 30000 ] && body=
  [ -n "$body" ] && break
  sleep 0.5
done
sleep 2
{ echo "### every captured request: file, bytes, has-tools, HOME_CONTRACT_MARKER, PROJECT_MARKER"
  for f in "$CAP"/[0-9]*.json; do printf '%s %s tools=%s home=%s project=%s\n' "$(basename "$f")" "$(wc -c <"$f")" "$(grep -c '"tools"' "$f")" "$(grep -o HOME_CONTRACT_MARKER "$f" | wc -l)" "$(grep -o PROJECT_MARKER "$f" | wc -l)"; done
} > "$TMP/allreq.txt"
[ -n "$body" ] && cp "$body" "$EVID/first-request-$LABEL.json"
tmux -L "$SOCK" capture-pane -p -t 0 > "$TMP/pane.txt" 2>/dev/null
{
  echo "### interactive pane after launch:"; sed '/^\s*$/d' "$TMP/pane.txt" | head -40
  if [ -z "$body" ]; then echo "RESULT: NO MODEL REQUEST CAPTURED"; exit 2; fi
  echo "### main agent request (largest request carrying the brief): $(basename "$body")"
  echo "HOME_CONTRACT_MARKER occurrences: $(grep -o HOME_CONTRACT_MARKER "$body" | wc -l)"
  echo "PROJECT_MARKER occurrences: $(grep -o PROJECT_MARKER "$body" | wc -l)"
  echo "request bytes: $(wc -c < "$body")"
  cat "$TMP/allreq.txt"
} >> "$EVID/full-launch-$LABEL.txt" 2>&1
cat "$EVID/full-launch-$LABEL.txt"
