#!/usr/bin/env bash
# Evidence driver: runs the COMPLETE pi launch line the real bin/fm-spawn.sh
# generates (including its per-task -e extension) in a real interactive pty
# (private tmux server) inside a worktree nested in a firstmate home, with pi's
# provider pointed at a local capture server. Spends no model tokens.
# Usage: drive-pi-full-launch.sh <code-root> <label>
set -u
ROOT=$1 LABEL=$2
. "$ROOT/tests/fixtures.sh"
EVID=${EVID:?}
TMP=$(mktemp -d /tmp/fm-nest-pi.XXXXXX); SOCK="fmnestpi-$$"
cleanup() { tmux -L "$SOCK" kill-server 2>/dev/null; [ -n "${CAP_PID:-}" ] && kill "$CAP_PID" 2>/dev/null; sleep 2; rm -rf "$TMP" 2>/dev/null || { sleep 3; rm -rf "$TMP"; }; }
trap cleanup EXIT
H=$TMP/home; fm_test_spawn_home "$H" pi
printf 'HOME_CONTRACT_MARKER firstmate supervisor contract\n' > "$H/AGENTS.md"
P=$H/projects/proj; fm_git_init_commit "$P"
printf 'PROJECT_MARKER project rules\n' > "$P/AGENTS.md"; printf '.treehouse/\n' > "$P/.gitignore"
git -C "$P" add -A && git -C "$P" -c user.name=t -c user.email=t@t commit -qm project
fm_git_add_origin "$P" "$P.origin.git"
WT=$P/.treehouse/pool/1/proj; mkdir -p "$(dirname "$WT")"; git -C "$P" worktree add -q -b "wt-$LABEL" "$WT"
F=$(fm_test_make_spawn_fakebin "$TMP/fake"); fm_test_spawn_brief "$H" "t-$LABEL" "Reply with the word ok."
L=$TMP/launch.log; : > "$L"
FM_FAKE_LAUNCH_LOG="$L" PATH="$F:$PATH" fm_test_run_spawn "$H" "$WT" "$F" "t-$LABEL" "$P" --harness pi --mode no-mistakes --yolo off >/dev/null || { echo SPAWN FAILED; exit 1; }
LAUNCH=$(grep -m1 ' -e ' "$L")
CAP=$TMP/cap; mkdir -p "$CAP"; python3 "$EVID/capture.py" "$CAP" 2>/dev/null & CAP_PID=$!
i=0; while [ ! -s "$CAP/port" ] && [ $i -lt 100 ]; do sleep 0.05; i=$((i+1)); done; PORT=$(cat "$CAP/port")
AG=$TMP/pi-agent; mkdir -p "$AG"
printf '{"providers":{"cap":{"baseUrl":"http://127.0.0.1:%s/v1","api":"openai-completions","apiKey":"capture-only","models":[{"id":"m"}]}}}\n' "$PORT" > "$AG/models.json"
printf '{"defaultProvider":"cap","defaultModel":"m"}\n' > "$AG/settings.json"
{ echo "cd $(printf '%q' "$WT")"; echo "export PI_CODING_AGENT_DIR=$(printf '%q' "$AG") PI_OFFLINE=1"; printf '%s\n' "$LAUNCH"; } > "$TMP/run.sh"
tmux -L "$SOCK" new-session -d -x 200 -y 50 "bash --norc $TMP/run.sh; sleep 30"
body=
for _ in $(seq 1 120); do body=$(grep -l 'Reply with the word ok' "$CAP"/[0-9]*.json 2>/dev/null | head -n1); [ -n "$body" ] && break; sleep 0.5; done
sleep 1; tmux -L "$SOCK" capture-pane -p -t 0 > "$TMP/pane.txt"
{ echo "### case: pi $LABEL (worktree nested in home)"; echo "### launch line generated by fm-spawn:"; printf '%s\n' "$LAUNCH"
  echo "### interactive pane after launch:"; sed '/^\s*$/d' "$TMP/pane.txt" | tail -15
  if [ -z "$body" ]; then echo "RESULT: NO MODEL REQUEST CAPTURED"; ls "$CAP"; exit 2; fi
  echo "### first model request carrying the brief: $(basename "$body") ($(wc -c <"$body") bytes)"
  echo "HOME_CONTRACT_MARKER occurrences: $(grep -o HOME_CONTRACT_MARKER "$body" | wc -l)"
  echo "PROJECT_MARKER occurrences: $(grep -o PROJECT_MARKER "$body" | wc -l)"
} > "$EVID/pi-full-launch-$LABEL.txt" 2>&1
cat "$EVID/pi-full-launch-$LABEL.txt"
